services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    networks:
      - fake-news-mlops
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    networks:
      - fake-news-mlops
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9095", "--list"]
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-setup:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - fake-news-mlops
    restart: on-failure
    command:
      - bash
      - -lc
      - |
        echo "Waiting Kafka..."
        until kafka-topics --bootstrap-server kafka:9092 --list >/dev/null 2>&1; do
          sleep 1
        done

        echo "Creating topics..."
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic raw_news --partitions 3 --replication-factor 1 --config retention.ms=604800000
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic scored_news --partitions 3 --replication-factor 1 --config retention.ms=604800000

        echo "Topics:"
        kafka-topics --bootstrap-server kafka:9092 --list

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    networks:
      - fake-news-mlops
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  postgres:
    image: postgres:16
    networks:
      - fake-news-mlops
    environment:
      POSTGRES_DB: fake_news
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./news_database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fake_news"]
      interval: 5s
      timeout: 10s
      retries: 10

  fake_news_detector:
    build:
      context: .
      dockerfile: news_scorer/Dockerfile
    networks:
      - fake-news-mlops
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_RAW_TOPIC: "raw_news"
      KAFKA_SCORED_TOPIC: "scored_news"
      WEIGHTS_DIR: "/app/model"
      THRESHOLD: "0.5"
    depends_on:
      kafka:
        condition: service_healthy
      kafka-setup:
        condition: service_started

  database_logger:
    build:
      context: .
      dockerfile: database_logger/Dockerfile
    networks:
      - fake-news-mlops
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_SCORED_TOPIC: "scored_news"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-setup:
        condition: service_started

  interface:
    build:
      context: .
      dockerfile: interface/Dockerfile
    networks:
      - fake-news-mlops
    environment:
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: "raw_news"

      PG_HOST: "postgres"
      PG_PORT: "5432"
      PG_DB: "fake_news"
      PG_USER: "user"
      PG_PASSWORD: "password"
      PG_TABLE: "news_predictions"
    depends_on:
      kafka:
        condition: service_healthy
      kafka-setup:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - "8501:8501"

  dagster:
    build:
      context: .
      dockerfile: dagster/Dockerfile
    networks:
      - fake-news-mlops
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DAGSTER_HOME: /app/dagster_home
    volumes:
      - dagster_home:/app/dagster_home
    ports:
      - "3000:3000"

  dagster-daemon:
    build:
      context: .
      dockerfile: dagster/Dockerfile
    networks:
      - fake-news-mlops
    depends_on:
      dagster:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      DAGSTER_HOME: /app/dagster_home
    volumes:
      - dagster_home:/app/dagster_home
    command: ["dagster-daemon", "run"]

networks:
  fake-news-mlops:
    name: fake-news-mlops
    driver: bridge

volumes:
  pg_data:
  dagster_home:
